/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_purp_mynt_Hooks */

#ifndef _Included_me_purp_mynt_Hooks
#define _Included_me_purp_mynt_Hooks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_purp_mynt_Hooks
 * Method:    setupRing
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_me_purp_mynt_Hooks_setupRing
(JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_me_purp_mynt_Hooks_close
(JNIEnv *, jobject);

/*
 * Class:     me_purp_mynt_Hooks
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_me_purp_mynt_Hooks_connect
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     me_purp_mynt_Hooks
 * Method:    accept
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_me_purp_mynt_Hooks_accept
        (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
