/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_mynt_Hooks */

#ifndef _Included_com_github_mynt_Hooks
#define _Included_com_github_mynt_Hooks
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_github_mynt_Hooks_connect
  (JNIEnv *, jobject, jint, jobject, jobject, jstring, jint);

JNIEXPORT void JNICALL Java_com_github_mynt_Hooks_accept
  (JNIEnv *, jobject, jint, jobject, jobject, jstring, jint);

JNIEXPORT void JNICALL Java_com_github_mynt_Hooks_close
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_github_mynt_Hooks_read
  (JNIEnv *, jobject, jint, jobject, jint, jlong, jlong, jlong);

JNIEXPORT jboolean JNICALL Java_com_github_mynt_Hooks_write
  (JNIEnv *, jobject, jint, jobject, jint, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_github_mynt_Hooks_epoll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
