/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_lucas_mynt_Test */

#ifndef _Included_me_lucas_mynt_Test
#define _Included_me_lucas_mynt_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_lucas_mynt_Test
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_lucas_mynt_Test_printHello
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
